language: node_js
node_js: 
  - "v12.13.0"
branches:
  only: 
    - master
cache: 
  - npm
before_install:
  - npm install -g firebase-tools
script:
  - npm test
after_success: 
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
deploy:
  skip_cleanup: true
  provider: firebase
  project: cjy-diy