language: node_js
node_js: 
  - "v10.16.3"
before_install:
  - npm install -g firebase-tools
script:
  - npm test
after_success: 
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master